language: r
cache: packages

r:
  - oldrel
  - release
  - devel
notifications:
  email:
    recipients:
      - hobichhai@gmail.com
    on_success: change
    on_failure: change
git:
  depth: false
branches:
  only:
    - master
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
  deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true